spring:
  application:
    name: UserService
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:users
    generate-unique-name: false
    name: users
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

